# Generated by Django 4.2.27 on 2025-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurtka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=200)),
                ('rang', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skidka', models.IntegerField(default=0)),
            ],
        ),
    ]
