# Generated by Django 4.2.27 on 2025-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiyim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.CharField(max_length=200)),
                ('davlat', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=200)),
                ('rang', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skidka', models.IntegerField(default=0)),
                ('sotuvdagi_soni', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product/')),
                ('color', models.CharField(max_length=30)),
                ('skidka', models.IntegerField(default=0)),
                ('sotuvdagi_soni', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
