# Generated by Django 4.2.27 on 2025-12-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiyim', '0002_futbolka_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefon',
            name='skidka',
        ),
        migrations.RemoveField(
            model_name='telefon',
            name='sotuvdagi_soni',
        ),
        migrations.AddField(
            model_name='telefon',
            name='brend',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('iphone', 'Iphone')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefon',
            name='ram',
            field=models.CharField(choices=[('gb4', '4 Gb'), ('gb8', '8 Gb')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telefon',
            name='color',
            field=models.CharField(choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil')], max_length=30),
        ),
    ]
